# Generated by Django 2.2.16 on 2022-02-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0014_post_test_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='test_field',
        ),
    ]
