# Generated by Django 2.2.16 on 2022-02-22 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_remove_post_test_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='group',
            field=models.ForeignKey(blank=True, help_text='Выберите группу', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='groups', to='posts.Group', verbose_name='Группа'),
        ),
    ]
